#!/usr/bin/env bash
equ_pattern='^([A-Za-z0-9_]+)[[:space:]]+equ[[:space:]]+\$[[:space:]]*-[[:space:]]*([A-Za-z0-9_]+)[[:space:]]*$'
db_pattern='^([a-zA-Z0-9_]+):?[[:space:]]+db[[:space:]]+\"(.*)\"([[:space:]]*,[[:space:]]*([0-9]+))?[[:space:]]*$'
dq_pattern='^([a-zA-Z0-9_]+):?[[:space:]]+dq[[:space:]]+([0-9]+|0x[0-9a-fA-F]+)$'
label_pattern='^([.a-zA-Z0-9_]+):$'
mov_rr_pattern='^mov[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
mov_ri_pattern='^mov[[:space:]]+([er][a-z]{2}),[[:space:]]+(.*)$'
mem_pattern='^\[([^]]+)\]$'
mem_dest_pattern='^\[([^]]+)\],[[:space:]]+([er][a-z]{2})$'
imm_patterns='^([0-9]+|-?[0-9]+|0x[0-9a-fA-F]+)$'
xor_self_pattern='^xor[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
push_pop_pattern='^(push|pop)[[:space:]]+([er][a-z]{2})$'
arith_rr_pattern='^(add|sub|cmp|or|and)[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
arith_ri_pattern='^(add|sub|cmp|or|and)[[:space:]]+([er][a-z]{2}),[[:space:]]*(.*)$'
jump_pattern='^(je|jne|jg|jl|jge|jle|ja|jb|jae|jbe|jo|jno|js|jns|jmp)[[:space:]]+(.*)$'
loop_pattern='^(loop|loope|loopne)[[:space:]]+(.*)$'
unary_pattern='^(inc|dec|neg|not)[[:space:]]+([er][a-z]{2})$'
unary_mem_pattern='^(inc|dec|neg|not)[[:space:]]+\[([^]]+)\]$'
call_pattern='^call[[:space:]]+([.a-zA-Z0-9_]+)$'
mul_pattern='^(mul|div|idiv)[[:space:]]+([er][a-z]{2})$'
mul_mem_pattern='^(mul|div|idiv)[[:space:]]+\[([^]]+)\]$'
imul_pattern='^imul[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
imul3_pattern='^imul[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2}|\[[^]]+\]),[[:space:]]+(.*)$'
imul_mem_pattern='^imul[[:space:]]+([er][a-z]{2}),[[:space:]]+\[([^]]+)\]$'
lea_pattern='^lea[[:space:]]+([er][a-z]+),[[:space:]]+\[([a-zA-Z0-9_]+)\]$'
shift_pattern='^(shl|shr|sar)[[:space:]]+([er][a-z]{2}),[[:space:]]+([0-9]+)$'
shift_mem_pattern='^(shl|shr|sar)[[:space:]]+\[([^]]+)\],[[:space:]]+([0-9]+)$'
test_rr_pattern='^test[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
test_ri_pattern='^test[[:space:]]+([er][a-z]{2}),[[:space:]]+([0-9]+|0x[0-9a-fA-F]+)$'
movzx_pattern='^(movzx|movsx)[[:space:]]+([er][a-z]{2}),[[:space:]]+([ab][lh]|[cd][lh]|dil|sil|bpl|spl|[er][a-z]{2})$'
movsxd_pattern='^movsxd[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
arith_mem_imm_pattern='^(add|sub|and|or|xor|cmp)[[:space:]]+\[([^]]+)\],[[:space:]]+(.*)$'
setcc_pattern='^set(e|ne|a|ae|b|be|g|ge|l|le|z|nz|o|no|s|ns)[[:space:]]+([ab][lh]|[cd][lh]|[er][a-z]{2})$'
cmov_pattern='^cmov(e|ne|a|ae|b|be|g|ge|l|le|o|no|s|ns|p|np)[[:space:]]+([er][a-z]{2}),[[:space:]]+([er][a-z]{2})$'
movss_rr_pattern='^movss[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
movsd_rr_pattern='^movsd[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
addss_rr_pattern='^addss[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
addsd_rr_pattern='^addsd[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
mulss_rr_pattern='^mulss[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
mulsd_rr_pattern='^mulsd[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
subss_rr_pattern='^subss[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
subsd_rr_pattern='^subsd[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
divss_rr_pattern='^divss[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
divsd_rr_pattern='^divsd[[:space:]]+(xmm[0-9]+),[[:space:]]+(xmm[0-9]+)$'
movsd_mem_pattern='^movsd[[:space:]]+(xmm[0-9]+),[[:space:]]+\[([er][a-z]+)\]$'
cvtsd2si_pattern='^cvtsd2si[[:space:]]+([er][a-z]{2}),[[:space:]]+(xmm[0-9]+)$'

sse_mem_src_pattern='^(movss|movsd|addss|addsd|subss|subsd|mulss|mulsd|divss|divsd|comiss|comisd|ucomiss|ucomisd)[[:space:]]+(xmm[0-9]+),[[:space:]]+\[([^]]+)\]$'
sse_mem_dst_pattern='^(movss|movsd)[[:space:]]+\[([^]]+)\],[[:space:]]+(xmm[0-9]+)$'
cvtsi2s_reg_pattern='^(cvtsi2ss|cvtsi2sd)[[:space:]]+(xmm[0-9]+),[[:space:]]+([er][a-z]{2})$'
cvtsi2s_mem_pattern='^(cvtsi2ss|cvtsi2sd)[[:space:]]+(xmm[0-9]+),[[:space:]]+\[([^]]+)\]$'
cvtss2si_rr_pattern='^cvtss2si[[:space:]]+([er][a-z]{2}),[[:space:]]+(xmm[0-9]+)$'
cvtss2s_mem_pattern='^(cvtss2si|cvtsd2si)[[:space:]]+([er][a-z]{2}),[[:space:]]+\[([^]]+)\]$'
string_op_pattern='^(movsb|movsw|movsl|movsq|stosb|stosw|stosl|stosq|lodsb|lodsw|lodsl|lodsq|scasb|scasw|scasl|scasq|cmpsb|cmpsw|cmpsl|cmpsq|cld|std)$'
push_imm_pattern='^push[[:space:]]+(-?[0-9]+|0x[0-9a-fA-F]+)$'
push_equsym_pattern='^push[[:space:]]+([a-zA-Z0-9_]+)$'
push_mem_pattern='^push[[:space:]]+(qword[[:space:]]+)?\[([^]]+)\]$'
pop_mem_pattern='^pop[[:space:]]+(qword[[:space:]]+)?\[([^]]+)\]$'

# C-compiler instruction patterns
rep_pattern='^rep[[:space:]]+(movsb|movsw|movsl|movsq|stosb|stosw|stosl|stosq|lodsb|lodsw|lodsl|lodsq|scasb|scasw|scasl|scasq|cmpsb|cmpsw|cmpsl|cmpsq)$'
lea_mem_pattern='^lea[[:space:]]+([er][a-z]{2}),[[:space:]]+\[([^]]+)\]$'
mov_mem_imm_pattern='^mov[[:space:]]+(qword[[:space:]]+|dword[[:space:]]+|byte[[:space:]]+)?\[([^]]+)\],[[:space:]]+(-?[0-9]+|0x[0-9a-fA-F]+)$'
shift_cl_pattern='^(shl|shr|sar)[[:space:]]+([er][a-z]{2}),[[:space:]]+cl$'
setcc_mem_pattern='^set(e|ne|a|ae|b|be|g|ge|l|le|z|nz|o|no|s|ns)[[:space:]]+(byte[[:space:]]+)?\[([^]]+)\]$'
imul_ri_pattern='^imul[[:space:]]+([er][a-z]{2}),[[:space:]]+(-?[0-9]+|0x[0-9a-fA-F]+)$'

# movzx/movsx with memory source
movzx_mem_pattern='^(movzx)[[:space:]]+([er][a-z]{2}),[[:space:]]+(byte[[:space:]]+)?\[([^]]+)\]$'
movsx_mem_pattern='^(movsx)[[:space:]]+([er][a-z]{2}),[[:space:]]+(byte[[:space:]]+)?\[([^]]+)\]$'
movsxd_mem_pattern='^(movsxd)[[:space:]]+([er][a-z]{2}),[[:space:]]+\[([^]]+)\]$'

movzx_word_mem_pattern='^(movzx)[[:space:]]+([er][a-z]{2}),[[:space:]]+(word[[:space:]]+)?\[([^]]+)\]$'
movsx_word_mem_pattern='^(movsx)[[:space:]]+([er][a-z]{2}),[[:space:]]+(word[[:space:]]+)?\[([^]]+)\]$'

align_pattern='^\.(align|balign|p2align)[[:space:]]+([0-9]+)$'
